### ISSUE TITLE
make location id search work or remove

### ISSUE THREAD

**Issue by sethvincent** [openaq/openaq-metadata-editor#26]
The [mockups](https://github.com/openaq/openaq-metadata-editor/issues/2) have a search bar on the home page for searching via location id, country, or city.

We have a countries filter so it doesn't make sense to both search by country and filter by country. We could possibly add a city filter as well.

I wonder what circumstances would lead someone to know the id and want to do a search by id. It seems unlikely. It may be best to remove the search box, replace it with a site header, and make the filters the one place where users can specify country, city, etc.

**Comment by kamicut** [comment]
@sethvincent I agree that search by id would be weird. If you know the ID, you probably have bookmarked the page for that station (or would want to "favorite" it to your account). I think that yes, if we add city filters it could be redundant to have a search bar, but it would depend on what's the quickest user interaction to get to the page they want. 

If we do have a city filter, we should have the cities filtered by the selection in the country list. So maybe it should be a combined component.

**Comment by sethvincent** [comment]
added issue for filtering by city (#27) and for revising the home view header (#28). closing this as we'll track using those two issues.
