### ISSUE TITLE
Form validation on save only

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-metadata-editor#52]
Proposal to perform validation of the form on save only.

## Current behavior
Any edit to the form triggers form validation and immediately highlights the required fields in bright red.

## Expected behavior
After filling in the form and hitting save, the form is validated, highlighting the errors.

**Comment by necoline** [comment]
@sethvincent What was the reason behind [validating on propUpdate ](https://github.com/openaq/openaq-metadata-editor/blob/acc3d820390c320a139678f412f68c9558f6ce32/app/assets/scripts/views/location-edit.js#L90)
From what I can tell, if we are validating the form before we update [here](https://github.com/openaq/openaq-metadata-editor/blob/acc3d820390c320a139678f412f68c9558f6ce32/app/assets/scripts/views/location-edit.js#L493), it works just fine. 
I know on our call, you mentioned some trickery with validating json objects, so maybe I'm overlooking something?

**Comment by sethvincent** [comment]
@necoline great, it looks like that’s an easier fix than I expected.

**Comment by necoline** [comment]
You can see the fix here: #55

**Comment by sethvincent** [comment]
closed by #55
