### ISSUE TITLE
Make references to location name consistent across ui

### ISSUE THREAD

**Issue by sethvincent** [openaq/openaq-metadata-editor#61]
Feedback we received:

> The "Location" and "Name" should be consistently described. For instance, in one place the 'Centario' is called a "Location" and another, it says "Name." Perhaps it could say "Location Name" instead in the second, lower spot?

We may want to change the title in the schema to support this https://github.com/openaq/openaq-data-format/blob/master/schemas/location.json#L20

Or make other changes to make things more consistent.

**Comment by necoline** [comment]
What is the distinction between location and the metadata name?
I understand the feedback in the context of the example given, but the example below the name location and the metadata provide very different values.
![image](https://user-images.githubusercontent.com/20410256/65062130-61e8d680-d949-11e9-8185-2a93d4f24d51.png)

If the user is concerned that these should be consistent when they are actually different pieces of data, maybe we should rename the metadata name to reflect its distinct purpose? We could also go the extra mile and add a tooltip describing what the metadata name should reflect.

**Comment by sethvincent** [comment]
@necoline That's a really good point. My initial thought is that we should remove the `Location: AD0942A` line altogether. I believe it's something that's populated by openaq-fetch and not something that can be changed here.

**Comment by olafveerman** [comment]
`location` is the name used by the data provider. I think it's useful keep it as a read-only field. It's the easiest way to match a station in OpenAQ to a station in the dataset of the data provider.

**Comment by necoline** [comment]
If I understand this correctly, ```location``` is the point of reference for the station and ```name``` is more of a user-friendly nickname that describes the site detailed under site details? 

What is the difference between a site and a station?

**Comment by necoline** [comment]
Per my conversation with @olafveerman, we can add clarification regarding the location and name by:
- [] updating the help text to reflect the purpose of the name
- [] add a sentence to the form header stating that the block content is from the data-provider and not subject to change
-[] remove the location type to reflect the static nature of the content
