### ISSUE TITLE
render field descriptions as help text

### ISSUE THREAD

**Issue by sethvincent** [openaq/openaq-metadata-editor#62]
The location schema has descriptions for all the fields, for example: https://github.com/openaq/openaq-data-format/blob/master/schemas/location.json#L168

We may want to make small edits to the schema descriptions as needed.

**Comment by necoline** [comment]
Where should the description fields be added? Is this issue in reference to 

> "Inlet height should have units (meters) and should specify this is above ground, e.g. "Inlet height above ground (m)." Otherwise, this could be confused with altitude, etc."

**Comment by sethvincent** [comment]
closed by #64
