### ISSUE TITLE
Error on page load

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-metadata-editor#73]
https://metadata.openaq.org/ is deployed but seeing 'Error: domain option is required' on load. I think this is likely due to an autho0 var missing? Are we passing this through the build somehow? If you can point me to whatever we need to add here and how we want to pass it, I should be able to add it. Thanks!

cc/ @olafveerman @sethvincent @necoline

**Comment by sethvincent** [comment]
The config for production is here and yeah it looks like it needs to have some values filled in. I just made a pr for this: https://github.com/openaq/openaq-metadata-editor/pull/74

I think these steps will also need to be completed to finish the google integration for production: https://auth0.com/docs/connections/social/google

**Comment by jflasher** [comment]
Ok, I updated the apiURL with the prod URL and put in the Mapbox info as well. Two outstanding things (as far as I can tell).

- [x] I didn't add anything about Google auth but it looks to be working. I can 'log in' on the site and it shows my profile, etc. Can you confirm if it's working as expected or do I need to do anything else?
- [x] I'm using OpenAQ's public Mapbox token. However, it gets a 404 when trying to use the map style. Is there a public map style that can be used, or can OpenAQ be granted access to the map style used for staging, or I guess what's the best option here?

**Comment by sethvincent** [comment]
that map style is in the devseed account so i made a pr to change the token: https://github.com/openaq/openaq-metadata-editor/pull/78

the only thing about the google auth that doesn't work is that it doesn't retain the session across reloads of the page. as far as i know the setup instructions here are the way to make that work https://auth0.com/docs/connections/social/google

**Comment by jflasher** [comment]
Ok, created new GCP account tied to dev@ and hooked that up, looks to be working correctly. Thanks!
